#!/bin/bash

if ! which pdfpc >/dev/null 2>&1; then
	if which pacman >/dev/null 2>&1; then
		echo "Install pdfpc with pacman" >&2
		sudo pacman -S pdfpc
	elif which apt-get >/dev/null 2>&1; then
		echo "Install pdfpc with apt-get" >&2
		sudo apt-get install pdfpc
	fi
	if ! which pdfpc >/dev/null 2>&1; then
		echo "pdfpc not installed" >&2
		exit 1
	fi
fi

if [ -z "$1" ]; then
	echo "Have to give one argument: the directory containing presentation.pdf" >&2
	exit 2
fi

pdfpc "$1/presentation.pdf"
