name: Java

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build on jdk ${{ matrix.java }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        java: [11.x.x, 15.x.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java}}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin
      - name: Run the tests
        run: ./gradlew test
