name: Deploy

on:
  push:
    branches:
      - master

jobs:
  snapshot:
    name: Deploy a snapshot to JetBrains Marketplace

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Deploy to JetBrains Marketplace
        run: ./gradlew publishPlugin
        env:
          JETBRAINS_MARKETPLACE_TOKEN: ${{secrets.JETBRAINS_MARKETPLACE_TOKEN}}